name: Deploy Pages
on: 
  push:
    paths:
      - 'docs/**'
      - package.json
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Wrangler
        shell: bash
        run: npm install wrangler --save-dev
      - name: Build pages
        shell: bash
        run: npm run docs:build
      - name: Publish
        shell: bash
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
        run: npx wrangler pages deploy docs/.vitepress/dist/ --project-name lksj-avant-garde